#!/bin/sh

printf "\n\n==========================================="
printf "  INITIATE VENV AND INSTALL REQUIREMENTS   "
printf "==========================================\n\n"

source venv/bin/activate
sudo pip install -r requirements.txt

printf "\n\n====================================="
printf "           RUNNING TESTS             "
printf "=====================================\n\n"


coverage run manage.py test datapoints.models datapoints.views  --settings=polio.settings_test
coverage html --omit='venv/*.py,datapoints/tests/*.py,*__init__.py,*settings*.py,manage.py'

printf "\n\n====================================="
printf "           MIGRATING DATABASE           "
printf "=====================================\n\n"

# migrate db
python manage.py syncdb
python manage.py migrate

printf "\n\n====================================="
printf "           STARTING SERVER           "
printf "=====================================\n\n"

# start server
python manage.py runserver
