// data generated by http://beta.json-generator.com/NxSTEw4
//[
//    '{{repeat(15, 20)}}',
//    {
//        id: '{{objectId()}}',
//        username: '{{surname()}}',
//        first_name: '{{firstName()}}',
//        last_name: '{{surname()}}',
//        email: '{{email()}}',
//        isActive: '{{bool()}}',
//        groups: function() {
//            var values = [1,2,3,4];
//            var groups = [];
//            var randI = Math.floor(Math.random() * values.length);
//
//            groups.push(values[randI]);
//            if(Math.random() > 0.5)
//                groups.push(values[(randI+1) % values.length]);
//            if(Math.random() > 0.8)
//                groups.push(values[(randI+2) % values.length]);
//
//            return groups;
//        }
//    }
//]

// takes a list of strings ['a','b','c'] and creates an object like {a:'a', b:'b', c:'c'}

module.exports = {
    fields: {
        first_name: {
            weight: 1,
            title: "First Name"
        },
        last_name: { weight: 2 },
        username: { weight: 3 },
        date_joined: {
            title: 'Date Joined', // can override the schema's title for display purposes
            weight: 4, // lower weight = higher sort order
            format: 'MMM D, YYYY', // momentjs formatting for dates, numeraljs for numbers (?)
            //renderer: function(value, field, {moment, numeral}) { // custom renderer method
            //    //return moment(value).calendar()
            //    return moment(value).format('MMMM Do YYYY, h:mm:ss a');
            //}
        },
        password: {
            renderer: function() { return '******'; }
        },
        last_login: {
            format: 'MMM D, YYYY'
        },
        edit_link: {
            title: "Edit",
            key: 'id',
            renderer: function() { return 'edit me'; }
        }
    },
    schema: {
        "$schema": "http://json-schema.org/draft-04/schema#",
        title: "Users",
        type: "array",

        "defaultSortField": "last_name",
        "defaultSortDirection": "asc",
        "primaryKey": "id",
        
        items: {
            title: "User",
            type: "object",
            
            properties: {
                date_joined: {
                    title: "date_joined",
                    default: "2015-05-15 02:09:53.567367+00:00",
                    maxLength: null,
                    editable: true,
                    type: "string",
                    format: 'date-time',
                    display: {
                        weightForm: 3,
                        on_table: true,
                        weightTable: 3
                    }
                },
                email: {
                    title: "email",
                    default: "",
                    maxLength: 75,
                    editable: true,
                    type: "string",
                    display: {
                        weightForm: 5,
                        on_table: true,
                        weightTable: 5
                    }
                },
                first_name: {
                    default: "",
                    maxLength: 30,
                    title: "first_name",
                    editable: true,
                    type: "string",
                    display: {
                        weightForm: 6,
                        on_table: true,
                        weightTable: 6
                    }
                },
                groups: {
                    maxLength: null,
                    title: "groups",
                    editable: true,
                    type: "list",
                    display: {
                        weightForm: 7,
                        on_table: true,
                        weightTable: 7
                    },
                    items: {
                        enum: [ // oneOf matches one of multiple schemas, enum matches one of values
                            {
                                title: "UNICEF HQ",
                                value: 1
                            }
                        ]
                    }
                },
                id: {
                    default: "None",
                    maxLength: null,
                    title: "id",
                    editable: true,
                    type: "number",
                    display: {
                        weightForm: 9,
                        on_table: true,
                        weightTable: 9
                    }
                },
                is_active: {
                    default: true,
                    maxLength: null,
                    title: "is_active",
                    editable: true,
                    type: "boolean",
                    display: {
                        weightForm: 11,
                        on_table: true,
                        weightTable: 11
                    }
                },
                is_staff: {
                    default: false,
                    maxLength: null,
                    title: "is_staff",
                    editable: true,
                    type: "boolean",
                    display: {
                        weightForm: 12,
                        on_table: true,
                        weightTable: 12
                    }
                },
                is_superuser: {
                    default: false,
                    maxLength: null,
                    title: "is_superuser",
                    editable: true,
                    type: "boolean",
                    display: {
                        weightForm: 13,
                        on_table: true,
                        weightTable: 13
                    }
                },
                last_login: {
                    default: "2015-05-15 02:09:53.567582+00:00",
                    maxLength: null,
                    title: "last_login",
                    editable: true,
                    type: "string",
                    format: "date-time",
                    display: {
                        weightForm: 14,
                        on_table: true,
                        weightTable: 14
                    }
                },
                last_name: {
                    default: "",
                    maxLength: 30,
                    title: "last_name",
                    editable: true,
                    type: "string",
                    display: {
                        weightForm: 15,
                        on_table: true,
                        weightTable: 15
                    }
                },
                password: {
                    default: "",
                    maxLength: 128,
                    title: "password",
                    editable: true,
                    type: "string",
                    display: {
                        weightForm: 17,
                        on_table: true,
                        weightTable: 17
                    }
                },
                user_permissions: {
                    default: "",
                    maxLength: null,
                    title: "user_permissions",
                    editable: true,
                    type: "list",
                    display: {
                        weightForm: 21,
                        on_table: true,
                        weightTable: 21
                    }
                },
                username: {
                    default: "",
                    maxLength: 30,
                    title: "username",
                    editable: true,
                    type: "string",
                    display: {
                        weightForm: 22,
                        on_table: true,
                        weightTable: 22
                    }
                },
                age: {
                    type: "number"
                }
            }
        }
    },

    data: [
        {
            username: "AnonymousUser",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "-1",
            is_superuser: false,
            is_staff: false,
            last_login: "2014-10-29 18:36:49.051148+00:00",
            password: "",
            email: "",
            date_joined: "2014-10-29 18:36:49.051229+00:00",
            age: 999
        },
        {
            username: "ben",
            first_name: "Ben",
            last_name: "Lacker",
            is_active: true,
            id: "7",
            is_superuser: true,
            is_staff: true,
            last_login: "2015-01-12 18:02:03+00:00",
            password: "pbkdf2_sha256$12000$5Y62qZ9hYOg6$uo+blPbl6lLVrhrHwHgGQYFLmoCFk/zJM+hgP5p1Xgg=",
            email: "lacker@seedscientific.com",
            date_joined: "2015-01-12 18:02:03+00:00",
            age: 99
        },
        {
            username: "odk",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "6",
            is_superuser: true,
            is_staff: true,
            last_login: "2014-12-01 15:28:12+00:00",
            password: "pbkdf2_sha256$12000$ecBlwKl8ZYeo$aUmSf9g12y1zx//GpZStV/QoKBCTP6GyiaxJQQb9Lcs=",
            email: "",
            date_joined: "2014-12-01 15:28:12+00:00",
            age: 42
        },
        {
            username: "unicef_demo",
            first_name: "unicef",
            last_name: "demo",
            is_active: true,
            id: "8",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-02-02 19:29:15+00:00",
            password: "pbkdf2_sha256$12000$eXeghFlrvnSo$kWdDpJkTjom0GJq4dFutxzvovynhoDLTO8bMnRrznqU=",
            email: "",
            date_joined: "2015-02-02 19:29:15+00:00",
            age: 47
        },
        {
            username: "elliot",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "9",
            is_superuser: true,
            is_staff: true,
            last_login: "2015-02-26 17:59:04.575143+00:00",
            password: "pbkdf2_sha256$12000$OchTXelh7MIa$D3dhhACUG/kePt0fS8DVjTKm+WSV3D1b06ZvWcBKqO8=",
            email: "",
            date_joined: "2015-02-10 22:14:58+00:00",
            age: 21
        },
        {
            username: "sarah",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "5",
            is_superuser: true,
            is_staff: true,
            last_login: "2015-02-25 18:36:02.856379+00:00",
            password: "pbkdf2_sha256$12000$talVuAWvRCDX$XrYnmXINZii12mIk1teebGMJ98aN5MIWOriaSVCiIpQ=",
            email: "",
            date_joined: "2014-11-03 20:16:13+00:00",
            age: 21
        },
        {
            username: "Stephane",
            first_name: "Stephane",
            last_name: "Vouillamoz",
            is_active: true,
            id: "20",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-04-08 14:47:33.243192+00:00",
            password: "pbkdf2_sha256$12000$9QXVZbwGE41s$FtoUqm/cCYpmPMRErel5NI2GidkyKzglh/1BKYzXAmg=",
            email: "sv@novel-t.ch",
            date_joined: "2015-04-03 14:03:31+00:00",
            age: 21
        },
        {
            username: "bret",
            first_name: "Bret",
            last_name: "Fontecchio",
            is_active: true,
            id: "23",
            is_superuser: true,
            is_staff: false,
            last_login: "2015-04-13 14:49:39+00:00",
            password: "pbkdf2_sha256$12000$18vij2sKIB68$eg7ZuAXJxd9Efni8qByg1WF+VvSRfizjhRb13UHNK4E=",
            email: "bret@seedscientific.com",
            date_joined: "2015-04-13 14:30:32+00:00",
            age: 21
        },
        {
            username: "xiaodong",
            first_name: "Xiaodong",
            last_name: "Cai",
            is_active: true,
            id: "11",
            is_superuser: true,
            is_staff: false,
            last_login: "2015-04-13 14:26:53+00:00",
            password: "pbkdf2_sha256$12000$YVcOjZHaQSgp$F8yiD6mlVtAgrhJyX/SXRCzKWJ2xgB7/N+ezLFcCgno=",
            email: "xcai@unicef.org",
            date_joined: "2015-02-27 16:27:15+00:00",
            age: 21
        },
        {
            username: "user_dash1",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "18",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-04-10 17:18:15.771096+00:00",
            password: "pbkdf2_sha256$12000$ERVBYxuCYqGU$w2PnF+qekRCCamqDPN7lCyV+v36oN9CFy0ZBGxfsLyw=",
            email: "",
            date_joined: "2015-03-31 21:33:55+00:00",
            age: 21
        },
        {
            username: "sherine",
            first_name: "Sherine ",
            last_name: "Guirguis",
            is_active: true,
            id: "14",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-02-27 20:58:12.611538+00:00",
            password: "pbkdf2_sha256$12000$XUeKiRiCxp7X$Mg5uOigSxzOBuWkxC6T+qr5MTs461REHKBSO3iaYJpE=",
            email: "sguirguis@unicef.org",
            date_joined: "2015-02-27 16:35:49+00:00",
            age: 21
        },
        {
            username: "bo",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "2",
            is_superuser: true,
            is_staff: true,
            last_login: "2015-02-27 21:12:36.447406+00:00",
            password: "pbkdf2_sha256$12000$0oBvG1Gc42VB$EoYCx8ME1WnuW29SYJRRuf3TRN6tOaxAO923vRiIpn0=",
            email: "",
            date_joined: "2014-10-29 18:54:15+00:00",
            age: 21
        },
        {
            username: "Philippe",
            first_name: "Philippe",
            last_name: "Veltsos",
            is_active: true,
            id: "21",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-04-05 16:59:35.813237+00:00",
            password: "pbkdf2_sha256$12000$3pLymYEalgOu$qmKtuu0CaPcqdWV/DFyEmZ2pekcsD/enDnpu9WzsL5M=",
            email: "pv@novel-t.ch",
            date_joined: "2015-04-03 20:55:45+00:00",
            age: 21
        },
        {
            username: "asch",
            first_name: "Asch",
            last_name: "Harwood",
            is_active: true,
            id: "13",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-04-10 17:42:38.154422+00:00",
            password: "pbkdf2_sha256$12000$xZgstAOPtNey$/zF3B/3xrbuwX1QDODsiRRmHMrPJkNSm/cVR+KzltSs=",
            email: "aharwood@unicef.org",
            date_joined: "2015-02-27 16:32:38+00:00",
            age: 21
        },
        {
            username: "manish",
            first_name: "Manish",
            last_name: "Nag",
            is_active: true,
            id: "17",
            is_superuser: true,
            is_staff: true,
            last_login: "2015-04-10 18:57:03.213772+00:00",
            password: "pbkdf2_sha256$12000$mLIsZAIxs2Rp$kX8vFKPMZaOvMNVbssK8jVOV/3SHlhcsEgmnt8asKg4=",
            email: "nag@seedscientific.com",
            date_joined: "2015-03-23 16:16:57+00:00",
            age: 21
        },
        {
            username: "edward",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "15",
            is_superuser: true,
            is_staff: true,
            last_login: "2015-04-06 19:37:58.876277+00:00",
            password: "pbkdf2_sha256$12000$4Za6AwJyaqmM$NHubaCrih6V4nnQioAegdyMz6ZnhG8Et08mSnNOEl9I=",
            email: "",
            date_joined: "2015-03-12 19:43:25+00:00",
            age: 21
        },
        {
            username: "Vera",
            first_name: "Vera",
            last_name: "Savcic",
            is_active: true,
            id: "19",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-04-03 18:14:59.254212+00:00",
            password: "pbkdf2_sha256$12000$sWBS8Y8THpL6$hhkQJIXOv7Um7bY2zZaD9h8YBQ+r1XS6YP5GggWqe60=",
            email: "savcic@seedscientific.com",
            date_joined: "2015-04-02 20:36:51+00:00",
            age: 21
        },
        {
            username: "Seaman",
            first_name: "Vincent",
            last_name: "Seaman",
            is_active: true,
            id: "22",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-04-06 19:40:18.648544+00:00",
            password: "pbkdf2_sha256$12000$ACHnslZiRslw$YSNKnruuxU43xodwphytsVCAt6fnwxFkM0yUffeu040=",
            email: "Vincent.Seaman@gatesfoundation.org",
            date_joined: "2015-04-03 21:00:57+00:00",
            age: 21
        },
        {
            username: "noah",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "16",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-03-26 14:34:04.437817+00:00",
            password: "pbkdf2_sha256$12000$VTt8QvZBDu78$s+kkzwk1xgMYm8/z4NhEmclSpg4JyAlOZCsJs9v9sPU=",
            email: "",
            date_joined: "2015-03-23 13:52:09+00:00",
            age: 21
        },
        {
            username: "ojeba",
            first_name: "Ojeba",
            last_name: "Ogbolu",
            is_active: true,
            id: "10",
            is_superuser: true,
            is_staff: true,
            last_login: "2015-04-07 20:44:08.304367+00:00",
            password: "pbkdf2_sha256$12000$XvAaiPLgoSAL$m8HaekRqHAJcCD9dFMunmpROFvgC5GLporCjVPIe5Ps=",
            email: "ogbolu@seedscientific.com",
            date_joined: "2015-02-25 16:02:26+00:00",
            age: 21
        },
        {
            username: "Chenoweth",
            first_name: "Paul",
            last_name: "Chenoweth",
            is_active: true,
            id: "24",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-04-13 14:48:39.532181+00:00",
            password: "pbkdf2_sha256$12000$GPO3v7RRSAKI$FoV8BluOO2e/6tlHTZawjHbrL4f1EenQf3hD6h+U7+M=",
            email: "chenowethp@who.int",
            date_joined: "2015-04-13 14:35:25+00:00",
            age: 21
        },
        {
            username: "vincent",
            first_name: "Vincent",
            last_name: "Petit",
            is_active: true,
            id: "12",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-04-07 21:10:33.543895+00:00",
            password: "pbkdf2_sha256$12000$06umJDg5fY6C$OzO3RGPm7Koyv3O/KPxSmHnq8pq7BpxKxdxQ2NaQel8=",
            email: "vpetit@unicef.org",
            date_joined: "2015-02-27 16:31:30+00:00",
            age: 21
        },
        {
            username: "john",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "1",
            is_superuser: true,
            is_staff: true,
            last_login: "2015-04-23 18:12:28.372189+00:00",
            password: "pbkdf2_sha256$12000$Rs9EXYU0yypm$vXBumLxL5YGbPX0GuEMtY8LPF500UyxjCQgHLRvERfs=",
            email: "dingee@seedscientific.com",
            date_joined: "2014-10-29 18:35:31.679657+00:00",
            age: 21
        },
        {
            username: "evan",
            first_name: "",
            last_name: "",
            is_active: true,
            id: "3",
            is_superuser: false,
            is_staff: false,
            last_login: "2015-05-07 20:52:01.488463+00:00",
            password: "pbkdf2_sha256$12000$mIKulUdMwapl$p6gXq2sWkqxuq9CvBhKQZI5iKt/SY88fc5OziCo/o/Y=",
            email: "",
            date_joined: "2014-10-29 18:54:49.917383+00:00",
            age: 21
        }
    ]
};