-- INSERT INTO datapoint_with_computed
-- (indicator_id,region_id,campaign_id,value,cache_job_id)
--
-- SELECT DISTINCT
-- denom.master_indicator_id
-- ,denom.region_id
-- ,denom.campaign_id
-- ,(CAST(num_whole.value as FLOAT) - CAST(num_part.value as FLOAT)) / NULLIF(CAST(denom.value AS FLOAT),0) as calculated_value
-- ,$1
-- FROM (
--     SELECT
--       cic.indicator_id as master_indicator_id
--       ,ad.region_id
--       ,ad.indicator_id
--       ,ad.campaign_id
--       ,ad.value
--       ,ad.cache_job_id
--   FROM _tmp_agg_datapoint ad
--   INNER JOIN calculated_indicator_component cic
--   ON cic.indicator_component_id = ad.indicator_id
--   AND calculation = 'PART_OF_DIFFERENCE'
-- ) num_part
--
-- INNER JOIN (
--     SELECT
--       cic.indicator_id as master_indicator_id
--       ,ad.region_id
--       ,ad.indicator_id
--       ,ad.campaign_id
--       ,ad.value
--       ,ad.cache_job_id
--     FROM _tmp_agg_datapoint ad
--     INNER JOIN calculated_indicator_component cic
--     ON cic.indicator_component_id = ad.indicator_id
--     AND calculation = 'WHOLE_OF_DIFFERENCE'
-- ) num_whole
-- ON num_part.master_indicator_id = num_whole.master_indicator_id
-- AND num_part.region_id = num_whole.region_id
-- AND num_part.campaign_id = num_whole.campaign_id
--
-- INNER JOIN (
--     SELECT
--       cic.indicator_id as master_indicator_id
--       ,ad.region_id
--       ,ad.indicator_id
--       ,ad.campaign_id
--       ,ad.value
--       ,ad.cache_job_id
--     FROM _tmp_agg_datapoint ad
--     INNER JOIN calculated_indicator_component cic
--     ON cic.indicator_component_id = ad.indicator_id
--     AND calculation = 'WHOLE_OF_DIFFERENCE_DENOMINATOR'
-- ) denom
-- ON num_whole.region_id = denom.region_id
-- AND num_whole.master_indicator_id = denom.master_indicator_id
-- AND num_whole.campaign_id = denom.campaign_id;
