module.exports = [{
	'id'                 : 1,
	'name'               : 'Nigeria',
	'region_type'        : 1,
  'builtin'            : true,
	'parent_region_id'   : null,
	'office_id'          : 1 ,
},
{
	'id'                 : 2,
	'name'               : 'Afghanistan',
	'region_type_id'        : 1,
  'builtin'            : true,
	'parent_region_id'   : null,
	'office_id'          : 2 ,
},
{
	'id'                 : 3,
	'name'               : 'Pakistan',
	'region_type_id'        : 1,
  'builtin'            : true,
	'parent_region_id'   : null,
	'office_id'          : 3 ,
},{
  'id': 4,
  'name': "Bauchi (Province)",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  'id': 5,
  'name': "Borno",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  'id': 6,
  'name': "Jigawa (Province)",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  id: 7,
  'name': "Kaduna",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  id: 8,
  'name': "Kano",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  id: 9,
  'name': "Kebbi",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  id: 10,
  'name': "Sokoto",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  id: 11,
  'name': "Yobe",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  id: 12,
  'name': "Zamfara",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  },
  {
  id: 13,
  'name': "Katsina",
  'office_id': 1,
  'parent_region_id': 1,
  'region_type_id'            : 2,
  'builtin'            : true,
  }
]

;
