# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Deleting model 'PaxListReportTraining'
        db.delete_table(u'source_data_paxlistreporttraining')

        # Deleting model 'PracticeVCMBirthRecord'
        db.delete_table(u'source_data_practicevcmbirthrecord')

        # Deleting model 'VCMBirthRecord'
        db.delete_table(u'source_data_vcmbirthrecord')

        # Deleting model 'PhoneInventory'
        db.delete_table(u'source_data_phoneinventory')

        # Deleting model 'PracticeVCMSummary'
        db.delete_table(u'source_data_practicevcmsummary')

        # Deleting model 'VCMSettlement'
        db.delete_table(u'source_data_vcmsettlement')

        # Deleting model 'KnowThePeople'
        db.delete_table(u'source_data_knowthepeople')

        # Deleting model 'ClusterSupervisor'
        db.delete_table(u'source_data_clustersupervisor')

        # Deleting model 'HealthCamp'
        db.delete_table(u'source_data_healthcamp')

        # Deleting model 'VCMSummary'
        db.delete_table(u'source_data_vcmsummary')

        # Deleting model 'VWSRegister'
        db.delete_table(u'source_data_vwsregister')

        # Deleting model 'PracticeVCMSettCoordinates'
        db.delete_table(u'source_data_practicevcmsettcoordinates')


    def backwards(self, orm):
        # Adding model 'PaxListReportTraining'
        db.create_table(u'source_data_paxlistreporttraining', (
            ('timestamp', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('nameofparticipant', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('title', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('emailaddr', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('state', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
        ))
        db.send_create_signal('source_data', ['PaxListReportTraining'])

        # Adding model 'PracticeVCMBirthRecord'
        db.create_table(u'source_data_practicevcmbirthrecord', (
            ('settlementcode', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('simserial', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('householdnumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vcmrilink', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('nameofchild', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('dob', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vcm0dose', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('dateofreport', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('vcmnamecattended', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('datereport', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('deviceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['PracticeVCMBirthRecord'])

        # Adding model 'VCMBirthRecord'
        db.create_table(u'source_data_vcmbirthrecord', (
            ('settlementcode', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('simserial', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('householdnumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vcmrilink', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('nameofchild', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('dob', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vcm0dose', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('dateofreport', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('vcmnamecattended', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('datereport', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('deviceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['VCMBirthRecord'])

        # Adding model 'PhoneInventory'
        db.create_table(u'source_data_phoneinventory', (
            ('lga', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('name', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('asset_number', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('colour_phone', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('telephone_no', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('state', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('deviceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
        ))
        db.send_create_signal('source_data', ['PhoneInventory'])

        # Adding model 'PracticeVCMSummary'
        db.create_table(u'source_data_practicevcmsummary', (
            ('settlementcode', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('census2_11mom', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_toomanyroundsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('date_implement', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('census2_11mof', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_toomanyroundsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vaxnewbornsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_newborn', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_afpcase', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('simserial', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noreasonm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noreasonf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('censusnewbornsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poliohascurem', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_pregnantmother', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poliohascuref', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_securitym', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_relbeliefsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_nofeltneedf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vaxnewbornsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_securityf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_nofeltneedm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_relbeliefsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_farmm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_mslscase', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_farmf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_childdiedf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_marketm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_marketf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_childdiedm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_sideeffectsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_sideeffectsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_rireferral', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('census12_59mom', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('group_spec_events_spec_zerodose', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_unhappywteamm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('group_msd_chd_msd_childsickm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_childsickf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_cmamreferral', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_soceventm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('msd_grp_choice', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_soceventf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('spec_grp_choice', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poldiffsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_otherprotectionf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_otherprotectionm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_vcmattendedncer', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poldiffsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_unhappywteamf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('census12_59mof', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vax2_11mof', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vax2_11mom', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_otherdisease', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_agedoutm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_agedoutf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_fic', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noconsentm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('deviceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noconsentf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vax12_59mom', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('censusnewbornsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_familymovedf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_familymovedm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noplusesm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('dateofreport', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('vax12_59mof', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noplusesf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_nogovtservicesm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_nogovtservicesf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_hhnotvisitedf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_playgroundm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_hhnotvisitedm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_playgroundf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poliouncommonm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poliouncommonf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('group_msd_chd_msd_schoolf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_schoolm', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['PracticeVCMSummary'])

        # Adding model 'VCMSettlement'
        db.create_table(u'source_data_vcmsettlement', (
            ('settlementcode', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('simserial', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('daterecorded', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('settlementname', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_accuracy', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_longitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vcmphone', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_altitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('deviceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('vcmname', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_latitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['VCMSettlement'])

        # Adding model 'KnowThePeople'
        db.create_table(u'source_data_knowthepeople', (
            ('brothers', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('sisters', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('prefferedcity', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('dob', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('state_country', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('citiesvisited', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('nameofpax', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['KnowThePeople'])

        # Adding model 'ClusterSupervisor'
        db.create_table(u'source_data_clustersupervisor', (
            ('lga', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vcm_data', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('hrop_endorsed', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('start_time', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('coord_smwg_meetings', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('fund_transparency', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('coord_rfp_meeting', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('supervisee_name', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('supervision_location_latitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('hrop_socialdata', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('vcm_birthtracking', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('ri_supervision', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('supervision_location_accuracy', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('hrop_special_pop', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('daterecorded', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('supervision_location_altitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('instruction', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('num_lgac', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('supervisor_title', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('supervision_location_longitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('state', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('supervisor_name', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('end_time', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('hrop_workplan_aligned', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vcm_supervision', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('hrop_activities_conducted', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('hrop_implementation', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('hrop_activities_planned', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('coord_vcm_meeting', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['ClusterSupervisor'])

        # Adding model 'HealthCamp'
        db.create_table(u'source_data_healthcamp', (
            ('nc_location', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('agencyname', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('start_time', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('num_patients', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementname', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('lga', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('appropriate_location', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('hc_photo', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_altitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('names', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('recorder_ri', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('daterecorded', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('ward', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('endtime', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('num_penta', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('townannouncer', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('hc_stockout', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('clinician2', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('clinician1', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('num_measles', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('settlementgps_accuracy', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('userid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('formhub_uuid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('crowdcontroller', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('num_opv', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('opvvaccinator', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('separatetally', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('megaphone', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_latitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('region', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('recorder_opv', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_longitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['HealthCamp'])

        # Adding model 'VCMSummary'
        db.create_table(u'source_data_vcmsummary', (
            ('settlementcode', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('census2_11mom', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_toomanyroundsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('date_implement', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('census2_11mof', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_toomanyroundsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vaxnewbornsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_newborn', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_afpcase', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('simserial', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noreasonm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noreasonf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('censusnewbornsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poliohascurem', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_pregnantmother', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poliohascuref', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_securitym', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_relbeliefsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_nofeltneedf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vaxnewbornsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_securityf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_nofeltneedm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_relbeliefsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_farmm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_mslscase', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_farmf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_childdiedf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_marketm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_marketf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_childdiedm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_sideeffectsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_sideeffectsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_rireferral', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('census12_59mom', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('group_spec_events_spec_zerodose', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_unhappywteamm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('group_msd_chd_msd_childsickm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_childsickf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_cmamreferral', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_soceventm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('msd_grp_choice', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_soceventf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('spec_grp_choice', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poldiffsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_otherprotectionf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_otherprotectionm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_vcmattendedncer', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poldiffsm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_unhappywteamf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('census12_59mof', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vax2_11mof', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vax2_11mom', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_otherdisease', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_agedoutm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_agedoutf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_spec_events_spec_fic', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noconsentm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('deviceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noconsentf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vax12_59mom', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('censusnewbornsf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_familymovedf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_familymovedm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noplusesm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('dateofreport', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('vax12_59mof', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_noplusesf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_nogovtservicesm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_nogovtservicesf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_hhnotvisitedf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_playgroundm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_hhnotvisitedm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_playgroundf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poliouncommonm', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_poliouncommonf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('group_msd_chd_msd_schoolf', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('group_msd_chd_msd_schoolm', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['VCMSummary'])

        # Adding model 'VWSRegister'
        db.create_table(u'source_data_vwsregister', (
            ('simserial', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('lname_vws', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('personal_phone', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('fname_vws', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('wardcode', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('deviceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('acceptphoneresponsibility', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('datephonecollected', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['VWSRegister'])

        # Adding model 'PracticeVCMSettCoordinates'
        db.create_table(u'source_data_practicevcmsettcoordinates', (
            ('settlementcode', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('simserial', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('daterecorded', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('process_status', self.gf('django.db.models.fields.related.ForeignKey')(to=orm['source_data.ProcessStatus'])),
            ('settlementname', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_accuracy', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('submissiondate', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('created_at', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime(2015, 5, 20, 0, 0))),
            ('meta_instanceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_longitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('vcmphone', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_altitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('phonenumber', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('deviceid', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('key', self.gf('django.db.models.fields.CharField')(max_length=255, unique=True)),
            ('vcmname', self.gf('django.db.models.fields.CharField')(max_length=255)),
            ('settlementgps_latitude', self.gf('django.db.models.fields.CharField')(max_length=255)),
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('request_guid', self.gf('django.db.models.fields.CharField')(max_length=255)),
        ))
        db.send_create_signal('source_data', ['PracticeVCMSettCoordinates'])


    models = {
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'auth.user': {
            'Meta': {'object_name': 'User'},
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Group']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Permission']"}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'datapoints.campaign': {
            'Meta': {'ordering': "('-start_date',)", 'unique_together': "(('office', 'start_date'),)", 'object_name': 'Campaign', 'db_table': "'campaign'"},
            'campaign_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.CampaignType']"}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'office': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Office']"}),
            'slug': ('autoslug.fields.AutoSlugField', [], {'unique': 'True', 'max_length': '50', 'populate_from': "'get_full_name'", 'unique_with': '()'}),
            'start_date': ('django.db.models.fields.DateField', [], {})
        },
        u'datapoints.campaigntype': {
            'Meta': {'object_name': 'CampaignType', 'db_table': "'campaign_type'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '55'})
        },
        u'datapoints.indicator': {
            'Meta': {'ordering': "('name',)", 'object_name': 'Indicator', 'db_table': "'indicator'"},
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_reported': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'short_name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'slug': ('autoslug.fields.AutoSlugField', [], {'unique': 'True', 'max_length': '255', 'populate_from': "'name'", 'unique_with': '()'}),
            'source': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Source']"})
        },
        u'datapoints.office': {
            'Meta': {'object_name': 'Office', 'db_table': "'office'"},
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '55'})
        },
        u'datapoints.region': {
            'Meta': {'unique_together': "(('name', 'region_type', 'office'),)", 'object_name': 'Region', 'db_table': "'region'"},
            'created_at': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_high_risk': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'latitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'longitude': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'office': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Office']"}),
            'parent_region': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Region']", 'null': 'True'}),
            'region_code': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'region_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.RegionType']"}),
            'slug': ('autoslug.fields.AutoSlugField', [], {'unique': 'True', 'max_length': '255', 'populate_from': "'name'", 'unique_with': '()'}),
            'source': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Source']"})
        },
        u'datapoints.regiontype': {
            'Meta': {'object_name': 'RegionType', 'db_table': "'region_type'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '55'})
        },
        u'datapoints.source': {
            'Meta': {'object_name': 'Source', 'db_table': "'source'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'source_description': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'source_name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '55'})
        },
        'source_data.activityreport': {
            'Meta': {'object_name': 'ActivityReport'},
            'activity': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cd_attendance': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cd_hh_pending_issues': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cd_iec': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cd_local_leadership_present': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cd_num_hh_affected': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cd_num_vaccinated': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cd_pro_opv_cd': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cd_resolved': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cm_attendance': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cm_iec': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cm_num_caregiver_issues': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cm_num_husband_issues': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cm_num_positive': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cm_num_vaccinated': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cm_vcm_present': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cm_vcm_sett': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(2015, 5, 29, 0, 0)'}),
            'daterecorded': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'endtime': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_appropriate_location': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_clinician1': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_clinician2': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_crowdcontroller': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_nc_location': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_num_measles': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_num_opv': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_num_patients': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_num_penta': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_opvvaccinator': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_recorder_opv': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_recorder_ri': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_separatetally': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_stockout': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_team_allowances': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'hc_townannouncer': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'ipds_community_leader_present': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipds_issue_reported': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipds_issue_resolved': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipds_num_children': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipds_num_hh': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipds_other_issue': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipds_team': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ipds_team_allowances': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'key': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'lga': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'meta_instanceid': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'names': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'process_status': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['source_data.ProcessStatus']"}),
            'request_guid': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'settlementgps_accuracy': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'settlementgps_altitude': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'settlementgps_latitude': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'settlementgps_longitude': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'settlementname': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'start_time': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'submissiondate': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'title': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'ward': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        u'source_data.campaignmap': {
            'Meta': {'object_name': 'CampaignMap', 'db_table': "'campaign_map'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mapped_by': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['auth.User']"}),
            'master_object': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Campaign']"}),
            'source_object': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.SourceCampaign']", 'unique': 'True'})
        },
        u'source_data.document': {
            'Meta': {'ordering': "('-id',)", 'unique_together': "(('docfile', 'doc_text'),)", 'object_name': 'Document'},
            'created_by': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['auth.User']"}),
            'doc_text': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'docfile': ('django.db.models.fields.files.FileField', [], {'max_length': '100', 'null': 'True'}),
            'guid': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_processed': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'master_datapoint_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'source': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Source']"}),
            'source_datapoint_count': ('django.db.models.fields.IntegerField', [], {'null': 'True'})
        },
        u'source_data.documentdetail': {
            'Meta': {'object_name': 'DocumentDetail', 'db_table': "'document_detail'"},
            'db_model': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'document': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.Document']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'map_id': ('django.db.models.fields.IntegerField', [], {}),
            'master_dp_count': ('django.db.models.fields.IntegerField', [], {}),
            'master_object_id': ('django.db.models.fields.IntegerField', [], {}),
            'source_dp_count': ('django.db.models.fields.IntegerField', [], {}),
            'source_object_id': ('django.db.models.fields.IntegerField', [], {}),
            'source_string': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        u'source_data.etljob': {
            'Meta': {'ordering': "('-date_attempted',)", 'object_name': 'EtlJob'},
            'cron_guid': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'date_attempted': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(2015, 5, 29, 0, 0)'}),
            'date_completed': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'error_msg': ('django.db.models.fields.TextField', [], {'null': 'True'}),
            'guid': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            'success_msg': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'task_name': ('django.db.models.fields.CharField', [], {'max_length': '55'})
        },
        u'source_data.indicatormap': {
            'Meta': {'object_name': 'IndicatorMap', 'db_table': "'indicator_map'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mapped_by': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['auth.User']"}),
            'master_object': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Indicator']"}),
            'source_object': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.SourceIndicator']", 'unique': 'True'})
        },
        'source_data.processstatus': {
            'Meta': {'object_name': 'ProcessStatus'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'status_description': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'status_text': ('django.db.models.fields.CharField', [], {'max_length': '25'})
        },
        u'source_data.regionmap': {
            'Meta': {'object_name': 'RegionMap', 'db_table': "'region_map'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mapped_by': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['auth.User']"}),
            'master_object': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Region']"}),
            'source_object': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.SourceRegion']", 'unique': 'True'})
        },
        u'source_data.sourcecampaign': {
            'Meta': {'object_name': 'SourceCampaign', 'db_table': "'source_campaign'"},
            'campaign_string': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'document': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.Document']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'source_guid': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        'source_data.sourcedatapoint': {
            'Meta': {'unique_together': "(('source', 'source_guid', 'indicator_string'),)", 'object_name': 'SourceDataPoint', 'db_table': "'source_datapoint'"},
            'campaign_string': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'cell_value': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(2015, 5, 29, 0, 0)'}),
            'document': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.Document']"}),
            'guid': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'indicator_string': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'region_code': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'row_number': ('django.db.models.fields.IntegerField', [], {}),
            'source': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['datapoints.Source']"}),
            'source_guid': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'status': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['source_data.ProcessStatus']"})
        },
        u'source_data.sourceindicator': {
            'Meta': {'object_name': 'SourceIndicator', 'db_table': "'source_indicator'"},
            'document': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.Document']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'indicator_string': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'source_guid': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        u'source_data.sourceregion': {
            'Meta': {'object_name': 'SourceRegion', 'db_table': "'source_region'"},
            'country': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'document': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.Document']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_high_risk': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'lat': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'lon': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'parent_code': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'parent_name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'region_code': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'region_type': ('django.db.models.fields.CharField', [], {'max_length': '255', 'null': 'True'}),
            'source_guid': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        },
        u'source_data.sourceregionpolygon': {
            'Meta': {'object_name': 'SourceRegionPolygon', 'db_table': "'source_region_polygon'"},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'polygon': ('django.db.models.fields.TextField', [], {}),
            'shape_area': ('django.db.models.fields.FloatField', [], {}),
            'shape_len': ('django.db.models.fields.FloatField', [], {}),
            'source_region': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['source_data.SourceRegion']", 'unique': 'True'})
        },
        'source_data.vcmsummarynew': {
            'Meta': {'object_name': 'VCMSummaryNew'},
            'census12_59mof': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'census12_59mom': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'census2_11mof': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'census2_11mom': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'censusnewbornsf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'censusnewbornsm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'created_at': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime(2015, 5, 29, 0, 0)'}),
            'date_implement': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'dateofreport': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'deviceid': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_msd1': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_msd2': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax1': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax2': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax3': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax4': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax5': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax6': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax7': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax8': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'display_vax9': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_display_msd3': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_agedoutf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_agedoutm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_childdiedf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_childdiedm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_childsickf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_childsickm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_familymovedf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_familymovedm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_farmf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_farmm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_hhnotvisitedf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_hhnotvisitedm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_marketf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_marketm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_noconsentf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_noconsentm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_nofeltneedf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_nofeltneedm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_nogovtservicesf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_nogovtservicesm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_noplusesf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_noplusesm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_otherprotectionf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_otherprotectionm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_playgroundf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_playgroundm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_poldiffsf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_poldiffsm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_poliohascuref': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_poliohascurem': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_poliouncommonf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_poliouncommonm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_relbeliefsf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_relbeliefsm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_schoolf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_schoolm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_securityf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_securitym': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_sideeffectsf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_sideeffectsm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_soceventf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_soceventm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_toomanyroundsf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_toomanyroundsm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_unhappywteamf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_msd_unhappywteamm': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_msd_chd_tot_missed_check': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_afpcase': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_cmamreferral': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_fic': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_mslscase': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_newborn': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_otherdisease': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_pregnantmother': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_rireferral': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_vcmattendedncer': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'group_spec_events_spec_zerodose': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'key': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '255'}),
            'meta_instanceid': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'phonenumber': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'process_status': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['source_data.ProcessStatus']"}),
            'request_guid': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'settlementcode': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'simserial': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'spec_grp_choice': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'submissiondate': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_12_59months': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_2_11months': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_census': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_missed': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_newborns': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_vax': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_vax12_59mo': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_vax2_11mo': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'tot_vaxnewborn': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'vax12_59mof': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'vax12_59mom': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'vax2_11mof': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'vax2_11mom': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'vaxnewbornsf': ('django.db.models.fields.CharField', [], {'max_length': '255'}),
            'vaxnewbornsm': ('django.db.models.fields.CharField', [], {'max_length': '255'})
        }
    }

    complete_apps = ['source_data']